[p5.js hi ]Added image and typography
bocoup/p5.js-website pull request #107
Opened 2024-03-30 14:35 UTC by Surbhi-Pittie

2024-03-31 19:10 UTC, Divyansh013 requested changes

2024-03-31 19:10 UTC, Divyansh013 commented on src/content/reference/hi/p5/createImage.mdx
> +  <कोड>ऊंचाई</कोड> पैरामीटर नया सेट करने के लिए
don't translate code

2024-03-31 19:10 UTC, Divyansh013 commented on src/content/reference/hi/p5/get.mdx
> +  <a href="/reference/p5/पिक्सेल">पिक्सेल</a>। <ए का प्रयोग करें
anchor tag should be as it is

2024-04-01 07:32 UTC, Divyansh013 approved these changes

2024-04-01 07:34 UTC, Divyansh013 commented
@TanviKumar PTAL !

2024-04-02 10:48 UTC, TanviKumar approved these changes

2024-04-02 10:48 UTC, TanviKumar commented
@Qianqianye the PR can be merged

2024-04-03 02:43 UTC, merged

2024-04-03 02:43 UTC, Qianqianye commented
Thanks @Surbhi-Pittie @Divyansh013 @TanviKumar!