[p5.js hi ] Added Maths References
bocoup/p5.js-website pull request #112
Opened 2024-04-01 17:23 UTC by SanjaySinghRajpoot

2024-04-02 17:42 UTC, Divyansh013 requested changes

2024-04-02 17:42 UTC, Divyansh013 commented on src/content/reference/hi/p5/acos.mdx
> +  <p><code>acos()</code>, <a का व्युत्क्रम है
keep anchor tag as it is

2024-04-04 09:49 UTC, SanjaySinghRajpoot commented on src/content/reference/hi/p5/angleMode.mdx
> +  को कॉल करने से डिग्री पर स्विच हो जाता है। <code>angleMode(रेडियंस)</code> को कॉल करने से वापस रेडियंस पर स्विच हो जाता है।</p>
done

2024-04-04 09:52 UTC, SanjaySinghRajpoot commented on src/content/reference/hi/p5/acos.mdx
> +  <p><code>acos()</code>, <a का व्युत्क्रम है
done

2024-04-04 10:12 UTC, TanviKumar approved these changes

2024-04-04 12:56 UTC, merged