[p5.js - zh-Hans] Examples translation 01-05
bocoup/p5.js-website pull request #143
Opened 2024-04-06 02:29 UTC by douMax

Added examples translations 01-05

2024-04-06 02:45 UTC, unicar9 reviewed
总体没问题，除了一些排版外，另外中文翻译无需对应英文断行，可以稍作调整。

2024-04-06 02:45 UTC, unicar9 commented on src/content/examples/zh-Hans/01_Shapes_And_Color/00_Shape_Primitives/description.mdx
> +这个程序展示了基本图形原始函数的使用方法。
句号放最末，可以加上连接词“比如“更通顺

2024-04-06 02:45 UTC, unicar9 commented on src/content/examples/zh-Hans/01_Shapes_And_Color/01_Color/description.mdx
> +Colors can be represented in many different ways. This example demonstrates several options.
此处删除原文。

2024-04-06 02:45 UTC, unicar9 commented on src/content/examples/zh-Hans/02_Animation_And_Variables/00_Drawing_Lines/description.mdx
> +这个示例也展示了 HSB（色调-饱和度-亮度）的颜色模式 <a href="https://p5js.org/reference/#/p5/colorMode">colorMode</a>，所以第一个变量用来设置色调。
这个示例也展示了 HSB（色调-饱和度-亮度）的颜色模式 -> 这个示例也展示了 HSB（色调-饱和度-亮度）颜色模式 <a href="https://p5js.org/reference/#/p5/colorMode">colorMode</a> 的使用方法，

2024-04-06 02:45 UTC, unicar9 commented on src/content/examples/zh-Hans/02_Animation_And_Variables/03_Conditions/description.mdx
> +one-line-description: 在你的草图运行时，使用 if 和 else 语句来设置情境。
sketch -> always 翻译成绘图。

2024-04-06 02:45 UTC, unicar9 commented on src/content/examples/zh-Hans/05_Transformation/01_Rotate/description.mdx
> +one-line-description: 旋转坐标系统。
旋转坐标系统。-> 旋转坐标系。

2024-04-06 02:45 UTC, unicar9 commented on src/content/examples/zh-Hans/05_Transformation/00_Translate/description.mdx
> +<a href="https://p5js.org/reference/#/p5/translate">translate()</a> 函数将坐标系统的原点移动到指定位置。
坐标系统 -> 坐标系

2024-04-06 02:45 UTC, unicar9 commented on src/content/examples/zh-Hans/04_Input_Elements/01_Input_Button/description.mdx
> +one-line-description: 使用页面访问者的文本输入。
使用页面访问者的文本输入。-> 使用页面访问者的输入文本。是否更符合中文习惯？

2024-04-06 02:45 UTC, unicar9 commented on src/content/examples/zh-Hans/04_Input_Elements/01_Input_Button/description.mdx
> +通过使用 <a href="https://p5js.org/reference/#/p5.Element/createElement" target="_blank">createElement()</a>、<a href="https://p5js.org/reference/#/p5/createInput" target="_blank">createInput()</a> 和 <a h
文本输入 -> 输入文本

2024-04-06 02:45 UTC, unicar9 commented on src/content/examples/zh-Hans/04_Input_Elements/00_Image_Drop/description.mdx
> +<a href="https://p5js.org/reference/#/p5.Element/drop" target="_blank">drop()</a> 是一个 p5.js 元素方法，它在每次有文件加载到元素中时注册一个回调。上传的文件会被创建成一个 <a href="https://p5js.org/reference/#/p5.File" target="_blank">p5.Fi
回调 -> 回调函数

2024-04-06 02:45 UTC, unicar9 commented on src/content/examples/zh-Hans/03_Imported_Media/04_Create_Audio/description.mdx
> +用于创建一个音频播放器。本示例展示了播放器的控制按钮，
中文翻译不需要完全对应英文的分行方式。

2024-04-06 11:17 UTC, douMax commented
Updated

2024-04-06 11:50 UTC, unicar9 approved these changes
很棒！

2024-04-07 00:33 UTC, sproutleaf requested changes
有一些小地方要改的，谢谢！！

2024-04-07 00:33 UTC, sproutleaf commented on src/content/examples/zh-Hans/03_Imported_Media/00_Words/description.mdx
> +The <a href="https://p5js.org/reference/#/p5/text" target="_blank">text()</a> 函数用于将文本插入到画布中。你可以使用 <a href="https://p5js.org/reference/#/p5/loadFont" target="_blank">loadFont()</a> 和 <a href="https://
开头多了一个The~

2024-04-07 00:33 UTC, sproutleaf commented on src/content/examples/zh-Hans/03_Imported_Media/04_Create_Audio/description.mdx
> +用于创建一个音频播放器。本示例展示了播放器的控制按钮，
这应该没事！我点了一下右上角三点看view file，看出来的段子是不断的

2024-04-07 00:33 UTC, sproutleaf commented on src/content/examples/zh-Hans/04_Input_Elements/01_Input_Button/description.mdx
> +通过使用 <a href="https://p5js.org/reference/#/p5.Element/createElement" target="_blank">createElement()</a>、<a href="https://p5js.org/reference/#/p5/createInput" target="_blank">createInput()</a> 和 <a h
这里按照weijia的suggestion改一下 谢谢！

2024-04-07 00:33 UTC, sproutleaf commented on src/content/examples/zh-Hans/04_Input_Elements/01_Input_Button/description.mdx
> +one-line-description: 使用页面访问者的文本输入。
已改

2024-04-07 00:45 UTC, sproutleaf commented
哦哦还有red已经在https://github.com/bocoup/p5.js-website/pull/141/files给merge上去了，这个PR里就不用再加啦，谢谢！

2024-04-08 11:17 UTC, douMax commented
已经修改。目前这个 PR 里应该已经不包括 red 了。只有 examples 下的 01-05 @sproutleaf @unicar9

2024-04-09 18:25 UTC, merged

2024-04-09 18:25 UTC, Qianqianye commented
Looks great, thanks!