[p5.js - hi] Translate 01-05 examples
bocoup/p5.js-website pull request #147
Opened 2024-04-06 12:20 UTC by EshaanAgg

2024-04-08 01:04 UTC, TanviKumar requested changes

2024-04-08 11:51 UTC, EshaanAgg commented on src/content/examples/hi/05_Transformation/02_Scale/description.mdx
> +one-line-description: समन्वय प्रणाली पैमाने को संशोधित करें
Made the required changes. Thanks for the review.

2024-04-09 13:35 UTC, TanviKumar approved these changes

2024-04-09 19:13 UTC, Divyansh013 approved these changes

2024-04-10 00:07 UTC, TanviKumar commented
@Qianqianye this PR can be merged

2024-04-12 00:27 UTC, Qianqianye commented
Thanks, could you resolve the conflicts before we merge? Thanks! @EshaanAgg @TanviKumar @Divyansh013

2024-04-12 06:28 UTC, EshaanAgg commented
@Qianqianye @TanviKumar @Divyansh013 Resolved the conflicts!

2024-04-13 00:54 UTC, merged

2024-04-13 00:54 UTC, Qianqianye commented
Looks great, thanks!