[p5.js -es] Adding missing translations stuck in GitLocalize
bocoup/p5.js-website pull request #149
Opened 2024-04-06 19:18 UTC by DianaMGalindo

Hello all! 

This is to update two translations that got stuck in GitLocalize: 

- frameRate()
- getTargetFrameRate()

I will be also adding the translation of other **p5 reference entries** that have been distributed today. 

Thanks.

2024-04-07 03:29 UTC, Guirdo commented
Gracias Diana! 

CC: @holomorfo

2024-04-07 15:44 UTC, DianaMGalindo commented
Traducciones de **Batch 3** (content/examples/es/), listas para revisión:

- 06_Calculating_Values (5)
- 07_ Repetition(6)
- 08_ Listing_Data_with_Arrays(1)
- 09_ Angles_and_Motion(3)
- 10_ Games(3)
- 11_ 3D (7)

Gracias :)

2024-04-07 16:59 UTC, Guirdo requested changes
Gracias Diana! Te dejo algunas observaciones

2024-04-07 16:59 UTC, Guirdo commented on src/content/examples/es/09_Angles_And_Motion/00_Sine_Cosine/description.mdx
> +Este ejemplo demuestra las funciones matemáticas del <a href="https://en.wikipedia.org/wiki/Sine_and_cosine">seno and coseno</a>
Typo en "seno and coseno"

2024-04-07 16:59 UTC, Guirdo commented on src/content/examples/es/10_Games/00_Circle_Clicker/description.mdx
> +title: Clic de Círculos
Sugiero traducir el titulo a "Clicker circular", porque los clicker son un tipo de juego que se caracterizan por solo dar click repetidas veces en un objeto en la pantalla.

2024-04-07 16:59 UTC, Guirdo commented on src/content/reference/es/p5/background.mdx
> +  <p>La versión de<code> background()</code> con dos parámetros interpreta el primero como un valor de escala de grises. El segundo parámetro establece el valor alfa (transparencia).</p>
Corregir la posición del espacio
```suggestion
  <p>La versión de <code>background()</code> con dos parámetros interpreta el primero como un valor de escala de grises. El segundo parámetro establece el valor alfa (transparencia).</p>
```

2024-04-07 16:59 UTC, Guirdo commented on src/content/reference/es/p5/background.mdx
> +          function</p>
Este "function" esta demás

2024-04-07 16:59 UTC, Guirdo commented on src/content/reference/es/p5/background.mdx
> +          <p>cadena de caracteres que definen un color. Los formatos posibles incluye: numero rgb() or rgba(), porcentaje rgb() o rgba(), hexadecimal definidos por 3 dígitos o 6 dígitos. </p>
Typo en "numero rgb() _or_ rgba()"

2024-04-07 16:59 UTC, Guirdo commented on src/content/reference/es/p5/colorMode.mdx
> +  <p>Llamar a <code>colorMode</code> cambian la manera en que p5.js interpreta los valores de color.</p>
Sugiero lo siguiente, porque se habla de una sola cosa

```suggestion
  <p>Llamar a <code>colorMode</code> cambia la manera en que p5.js interpreta los valores de color.</p> 
```

2024-04-07 16:59 UTC, Guirdo commented on src/content/reference/es/p5/erase.mdx
> +  <p>erase() no tiene efecto en los dibujos realizados con las funciones <a href="/reference/p5/image">image()</a> y <a href="/reference/p5/background">background()</a>.</p>
Encerrar "erase()" entre etiquetas <code>

2024-04-07 19:21 UTC, DianaMGalindo commented
Gracias @Guirdo @holomorfo por los comentarios! He corregido lo que se ha sugerido :-)
Gracias :-)

2024-04-08 02:28 UTC, holomorfo requested changes
Hola @DianaMGalindo, muchas gracias por las traducciones, aquí te dejo unos comentarios. Saludos!
CC: @Guirdo

2024-04-08 02:28 UTC, holomorfo commented on src/content/reference/es/p5/background.mdx
> +          <p>cadena de caracteres que definen un color. Los formatos posibles incluye: numero rgb() or rgba(), porcentaje rgb() o rgba(), hexadecimal definidos por 3 dígitos o 6 dígitos. </p>
y número lleva tilde

2024-04-08 02:28 UTC, holomorfo commented on src/content/reference/es/p5/erase.mdx
> +      <p>un número ( en el rango 0-255) que representa la intensidad del borrado dada por el interior de la forma. Por defecto es 255, lo que indica máxima intensidad.</p>
Quitar el espacio extra
```suggestion
      <p>un número (en el rango 0-255) que representa la intensidad del borrado dada por el interior de la forma. Por defecto es 255, lo que indica máxima intensidad.</p>
```

2024-04-08 02:28 UTC, holomorfo commented on src/content/reference/es/p5/erase.mdx
> +      <p>un número ( en el rango 0-255) que representa la intensidad del borrado dada por el borde de la forma. Por defecto es 255, lo que indica máxima intensidad.</p>
igual quitar el espacio extra
```suggestion
      <p>un número (en el rango 0-255) que representa la intensidad del borrado dada por el borde de la forma. Por defecto es 255, lo que indica máxima intensidad.</p>
```

2024-04-08 02:28 UTC, holomorfo commented on src/content/reference/es/p5/fill.mdx
> +  <p>La versión de <code>fill()</code> con un parámetro interpreta el valor de tres maneras. Si el parámetro es un <code>Number</code> (número), se interpreta como un valor de escala de grises. Si el
quitar doble espacio blanco
```suggestion
  <p>La versión de <code>fill()</code> con un parámetro interpreta el valor de tres maneras. Si el parámetro es un <code>Number</code> (número), se interpreta como un valor de escala de grises. Si el parámetro es un <code>String</code> (cadena de caracteres), se interpreta como una cadena de color CSS (colores predefinidos de CSS). También se puede proporcionar un objeto <a href="/reference/p5/p5.Color">p5.Color</a> para establecer el color de relleno.</p>
```

2024-04-08 02:28 UTC, holomorfo commented on src/content/reference/es/p5/frameRate.mdx
> +  <p>Si se pasa un argumento numérico a la función  <code>frameRate()</code>, por ejemplo: <code>frameRate(30)</code>, esta intentará  dibujar 30 cuadros por segundo, o 30 FPS (Frames Per Second en i
doble espacio
```suggestion
  <p>Si se pasa un argumento numérico a la función <code>frameRate()</code>, por ejemplo: <code>frameRate(30)</code>, esta intentará  dibujar 30 cuadros por segundo, o 30 FPS (Frames Per Second en inglés). Se dice ‘intentará’ porque el número de cuadros que se pueden dibujar por segundo (velocidad) depende de las necesidades de procesamiento del boceto (sketch). La mayoría de computadores tiene una velocidad de cuadros predeterminada de 60FPS. Velocidades de cuadro de 24 FPS en adelante son suficientemente rápidas para animaciones fluidas.</p>
```

2024-04-08 16:13 UTC, DianaMGalindo commented
Hola @holomorfo¡ Gracias por tus sugerencias. Nunca hubiese visto esos pequeños detalles. He aceptado todas tus correcciones.

2024-04-08 20:57 UTC, Guirdo approved these changes
Muchas gracias, Diana! Aprobado 💯

2024-04-08 22:18 UTC, holomorfo commented
Muchas gracias! aprobado (y)

2024-04-08 22:18 UTC, holomorfo approved these changes

2024-04-08 22:28 UTC, Guirdo commented
Hi @Qianqianye @limzykenneth ! This PR is ready!

2024-04-08 22:30 UTC, merged

2024-04-08 22:31 UTC, Qianqianye commented
Thanks @DianaMGalindo @holomorfo @Guirdo!