[p5.js - es] Translate Examples and Contributor Docs
bocoup/p5.js-website pull request #150
Opened 2024-04-06 23:47 UTC by ninioArtillero

- **translate image drop**
- **translate input-botton**
- **translate form elements**
- **translate translate :)**
- **translate rotate**
- **translate scale**
- **translate new first line comments**
- **copy access.md for translation**

2024-04-07 01:20 UTC, holomorfo requested changes
Hola Xavier, muchas gracias por tus traducciónes, te incluyo un par de comentarios. Saludos!

CC: @Guirdo

2024-04-07 01:20 UTC, holomorfo commented on src/content/contributor-docs/es/access.md
> +- PPublicar documentación e informes de nuestro trabajo que sigan las directrices WCAG, utilicen un lenguaje sencillo y se centren en los principiantes a partir de experiencias diversas (por ejemplo,
Quitar la doble P PPublicar

2024-04-07 01:20 UTC, holomorfo commented on src/content/examples/es/05_Transformation/01_Rotate/description.mdx
> +<a href="https://p5js.org/reference/#/p5/pop">pop()</a>
slavan en vez de salval

2024-04-07 03:55 UTC, Guirdo requested changes
Gracias Xavier! Te dejo algunas observaciones

2024-04-07 03:55 UTC, Guirdo commented on src/content/examples/es/04_Input_Elements/02_DOM_Form_Elements/description.mdx
Sugiero cambiar "forma" por "formulario", ya que "form" en este caso se refiero a un formulario (que se llena con datos) y también para no crear confusión con una forma geométrica.

2024-04-07 03:55 UTC, Guirdo commented on src/content/examples/es/05_Transformation/01_Rotate/description.mdx
> +<a href="https://p5js.org/reference/#/p5/pop">pop()</a>
Sugiero traducir "save" por "guardan"

2024-04-07 03:55 UTC, Guirdo commented on src/content/contributor-docs/es/access.md
> +- Traducir documentación y otros materiales a más idiomas, descentralizando el imperialismo lingüístico[^4] (por ejemplo, [Procesamiento en idioma kuna](https://medium.com/@ProcessingOrg/culture-as-t
En la frase "Processing in Kuna Language", _processing_ hace referencia al nombre de la fundación creadora de p5.js, por lo que no debe ser traducido.

2024-04-07 03:55 UTC, Guirdo commented on src/content/contributor-docs/es/access.md
> +- Hacer que los mensajes de error de p5.js sean más útiles y sirvan de apoyo para las personas que usan la herramienta (por ejemplo, el [Sistema de errores amigable de p5.js (FES)](https://github.com
En "Sistema de errores amigable de p5.js (FES)" sugiero aclarar que FES es por sus siglas en inglés

2024-04-07 03:55 UTC, Guirdo commented on src/content/contributor-docs/es/access.md
> +[^3]: Hay diferentes preferencias entre el lenguaje "persona primero" vs "identidad primero" dentro de la comunidad de personas con discapacidadesdes. Lee [Desempaquetando el debate sobre el lenguaje
Typo en "discapacidadesdes"

2024-04-07 13:55 UTC, ninioArtillero commented on src/content/examples/es/05_Transformation/01_Rotate/description.mdx
> +<a href="https://p5js.org/reference/#/p5/pop">pop()</a>
Creo que queda más claro usar "guardan". Lo corrijo también en los otros archivos

2024-04-07 13:56 UTC, ninioArtillero commented on src/content/examples/es/04_Input_Elements/02_DOM_Form_Elements/description.mdx
Buena observación, en este caso no entedí bien el contexto. Gracias

2024-04-07 14:26 UTC, ninioArtillero commented
Por cierto, noto que en otras carpetas el formato correcto del documento es `.mdx` y no `.md` (en los Contributor Docs). Estuvo bueno poder tener el syntax de markdown en mi editor. Voy a corregir las extensiones de los documentos y el formato del comentario de la primera línea; supongo que así se pasarán las pruebas automartizadas.

2024-04-07 16:05 UTC, Guirdo approved these changes
Muchas gracias, Xavier! Aprobado 💯

2024-04-08 02:33 UTC, holomorfo approved these changes
Aprobado, muchas gracias Xavier

2024-04-08 12:47 UTC, merged