[p5.js - zh - Hans] Update the translation of  About page and Index page
bocoup/p5.js-website pull request #160
Opened 2024-04-07 21:44 UTC by Tmicrd

2024-04-07 22:13 UTC, unicar9 commented on src/content/text-detail/zh-Hans/about.mdx
> +p5.js 是对学习编码和创作艺术友好的一个工具，它是免费且开源的 JavaScript 库，由一个包容的、培育型的社区建立。p5.js 欢迎艺术家、设计师、初学者、教育者，以及其他任何人！
p5.js 是对学习编码和创作艺术友好的一个工具 -> p5.js 是一款旨在帮助人们学习编程并进行艺术创作的友好工具。（让中文翻译更自然）

2024-04-07 22:14 UTC, unicar9 commented on src/content/text-detail/zh-Hans/about.mdx
> +p5.js 是对学习编码和创作艺术友好的一个工具，它是免费且开源的 JavaScript 库，由一个包容的、培育型的社区建立。p5.js 欢迎艺术家、设计师、初学者、教育者，以及其他任何人！
它是免费且开源的 JavaScript 库，由一个包容的、培育型的社区建立。-> 作为一个免费的开源 JavaScript 库，它由一个充满包容和关怀的社区共同打造。

2024-04-07 22:16 UTC, unicar9 commented on src/content/text-detail/zh-Hans/about.mdx
> +p5.js 是对学习编码和创作艺术友好的一个工具，它是免费且开源的 JavaScript 库，由一个包容的、培育型的社区建立。p5.js 欢迎艺术家、设计师、初学者、教育者，以及其他任何人！
p5.js 欢迎艺术家、设计师、初学者、教育者，以及其他任何人！-> 无论是艺术家、设计师、初学者、教育者，还是其他任何人，p5.js 都欢迎你的加入！（重心后置，更符合中文语序）

2024-04-07 22:25 UTC, unicar9 commented on src/content/text-detail/zh-Hans/about.mdx
> +p5.js 优先考虑无障碍、包容性、社区和快乐。这使得代码绘图就像在笔记本上绘图一样直观。p5.js 支持网络上的视听、交互和实验性作品。它支持多语言，并提供了丰富的文档和视觉示例。你可以立刻在网络编辑器中开始编码，并且许多教程可供参考。你也可以通过社区创建的库来扩展 p5.js 技能。p5.js 始终在寻找贡献者，并且感激各种形式的参与。
p5.js 优先考虑无障碍、包容性、社区和快乐。-> 参考：p5.js 非常重视无障碍性、包容性、社区共享和传递快乐。
这使得代码绘图就像在笔记本上绘图一样直观。-> 参考：它使得编程绘图像在笔记本上涂鸦一样直观。

2024-04-07 22:30 UTC, unicar9 commented on src/content/text-detail/zh-Hans/index.mdx
> +p5.js 是对学习编码和创作艺术友好的一个工具，它是免费且开源的 JavaScript 库，由一个包容的、培育型的社区建立。p5.js 欢迎艺术家、设计师、初学者、教育者，以及其他任何人！
同上可稍作修改。

2024-04-08 00:35 UTC, sproutleaf requested changes

2024-04-08 00:35 UTC, sproutleaf commented on src/content/text-detail/zh-Hans/about.mdx
> +- 我们优先将无障碍性作为社区关怀的基础实践。
无障碍性 -> 可及性

2024-04-08 00:35 UTC, sproutleaf commented on src/content/text-detail/zh-Hans/about.mdx
> +- 我们都是学习者，我们分享和珍惜各种知识。我们不假设知识，也不暗示某人应该已经知道。我们保持初学者的心态，相信新手和专家一样有价值。
我们不假设知识，也不暗示某人应该已经知道 -> 我们不假设或暗示某人应该已经了解相关知识

2024-04-08 00:35 UTC, sproutleaf commented on src/content/text-detail/zh-Hans/about.mdx
> +- 我们将冲突视为社区的自然组成部分，以及重新与我们的价值观对齐的邀请。我们共同维护和遵守我们的行为规范，以确保社区问责制。
我们将冲突视为社区中自然的一部分，并邀请大家通过冲突重新考量和对齐我们的价值。

2024-04-08 00:35 UTC, sproutleaf commented on src/content/text-detail/zh-Hans/about.mdx
> +[无障碍性声明](https://github.com/processing/p5.js/blob/main/contributor_docs/access.md)
无障碍性声明 -> 可及性声明

2024-04-08 02:09 UTC, sproutleaf approved these changes
辛苦了！

2024-04-08 02:20 UTC, unicar9 approved these changes
很棒！

2024-04-08 02:22 UTC, unicar9 commented
Tagging @Qianqianye @limzykenneth for merging! Thanks

2024-04-08 09:03 UTC, merged