[p5.js - zh-Hans] Examples translation 11-15
bocoup/p5.js-website pull request #162
Opened 2024-04-07 23:51 UTC by togekisse

2024-04-08 00:51 UTC, sproutleaf requested changes
谢谢，辛苦了！

2024-04-08 01:28 UTC, unicar9 commented on src/content/examples/zh-Hans/11_3D/01_Custom_Geometry/description.mdx
> +函数形状存储到一个可以高效和重复使用的 3D 模型中。
can be efficiently used and reused -> 可以高效利用和重复使用（漏掉了 used）

2024-04-08 01:34 UTC, unicar9 commented on src/content/examples/zh-Hans/11_3D/03_Orbit_Control/description.mdx
> +<a href="https://p5js.org/reference/#/p5/orbitControl" target="_blank">轨道控制</a>
<a href="https://p5js.org/reference/#/p5/orbitControl" target="_blank">轨道控制</a> 利用鼠标或触屏输入来调整 3D 素描中的摄像机方向。-> <a href="https://p5js.org/reference/#/p5/orbitControl" target="_blank">轨道控制</a> 是指
利用鼠标或触屏输入来调整 3D 绘图中的摄像机方向。（确实连接词，请把 sketch 都翻译为绘图）

2024-04-08 01:34 UTC, unicar9 commented on src/content/examples/zh-Hans/11_3D/03_Orbit_Control/description.mdx
> +利用鼠标或触屏输入来调整 3D 素描中的摄像机方向。要旋转摄像机，请左键点击并拖动鼠标，或在触屏上滑动。要平移摄像机，请右键点击并拖动鼠标，或在触屏上用多个手指滑动。要将摄像机移动到素描中心更近或更远的位置，请使用鼠标滚轮或在触屏上捏放。
要将摄像机移动到素描中心更近或更远的位置，-> 要将摄像机移动到绘图中心更近或更远的位置，

2024-04-08 01:36 UTC, unicar9 commented on src/content/examples/zh-Hans/11_3D/04_Filter_Shader/description.mdx
> +one-line-description: 用着色器操纵图像。
用着色器操纵图像。-> 用着色器处理图像。（如果操纵图像不是约定俗称的说法，请改为操作或者处理，听起来更自然）

2024-04-08 01:36 UTC, unicar9 commented on src/content/examples/zh-Hans/11_3D/04_Filter_Shader/description.mdx
> +title: 过滤器着色器
过滤器着色器 -> 滤镜着色器（正文里的翻译更容易理解）

2024-04-08 01:39 UTC, unicar9 commented on src/content/examples/zh-Hans/11_3D/04_Filter_Shader/description.mdx
> +滤镜着色器可以渲染画布上的任何内容。在这个示例中，它们被用来渲染视频。
滤镜着色器可以渲染画布上的任何内容。在这个示例中，它们被用来渲染视频。-> 滤镜着色器是一种将效果应用于画布上任何内容的方法。在这个示例中，滤镜效果被应用到一个视频上。（翻译有点偏离原文）

2024-04-08 01:42 UTC, unicar9 commented on src/content/examples/zh-Hans/11_3D/05_Adjusting_Positions_With_A_Shader/description.mdx
> +着色器可以调整形状顶点的位置，实现对 3D 模型的扭曲和动画。
实现对 3D 模型的扭曲和动画。-> 从而实现对 3D 模型的扭曲和动画处理。

2024-04-08 01:51 UTC, unicar9 commented on src/content/examples/zh-Hans/15_Math_And_Physics/02_Forces/description.mdx
> +one-line-description: 模拟多个物体在液体移动时受到的力。
模拟多个物体在液体移动时受到的力。-> 模拟多个物体在液体中移动时受到的力。

2024-04-08 01:55 UTC, unicar9 commented on src/content/examples/zh-Hans/14_Loading_And_Saving_Data/02_Table/description.mdx
> +one-line-description: 将数据存储为用逗号分隔的值。
将数据存储为用逗号分隔的值。-> 将数据存储为逗号分隔值（CSV）文件（单纯用逗号分隔的值在中文里比较奇怪）

2024-04-08 01:57 UTC, unicar9 commented on src/content/examples/zh-Hans/14_Loading_And_Saving_Data/01_JSON/description.mdx
> +one-line-description: 将数据存储在 JavaScript 对象表示法中。
将数据存储在 JavaScript 对象表示法中。-> 将数据存储在 JavaScript 对象表示法（JSON） 中。

2024-04-08 01:58 UTC, unicar9 commented on src/content/examples/zh-Hans/14_Loading_And_Saving_Data/00_Local_Storage/description.mdx
> +title: 局部存储
局部存储 -> 本地存储

2024-04-08 01:59 UTC, unicar9 commented on src/content/examples/zh-Hans/14_Loading_And_Saving_Data/00_Local_Storage/description.mdx
> +<a href="https://developer.mozilla.org/en-US/docs/Web/API/Window/localStorage" target="_blank">局部存储</a>。
局部存储 -> 本地存储

2024-04-08 02:05 UTC, unicar9 commented on src/content/examples/zh-Hans/15_Math_And_Physics/04_Game_Of_Life/description.mdx
> +生命游戏是由数学家 John Conway 创建的细胞自动机。细胞自动机是一种模拟类型。在生命游戏中，有一个网格细胞，其中每个细胞或死或活。在这个例子中，黑色方块代表活细胞，白色方块代表死细胞。随着模拟运行，细胞根据一组规则在死和活之间切换：
细胞自动机 -> 推荐加上原文，术语方便查阅：细胞自动机（cellular automaton）

2024-04-08 02:07 UTC, unicar9 commented on src/content/examples/zh-Hans/12_Advanced_Canvas_Rendering/02_Shader_As_A_Texture/description.mdx
> +<a href="https://itp-xstory.github.io/p5js-shaders/">p5.js 着色器</a>
要了解更多关于在 p5.js 中使用着色器的信息：<a href="https://itp-xstory.github.io/p5js-shaders/">p5.js 着色器</a> -> 要了解更多关于在 p5.js 中使用着色器的信息，请参阅：<a href="https://itp-xstory.github.io/p5js-shaders/">p5.js 着色器</a>
缺少连接词。

2024-04-09 09:09 UTC, unicar9 commented on src/content/examples/zh-Hans/11_3D/03_Orbit_Control/description.mdx
> +<a href="https://p5js.org/reference/#/p5/orbitControl" target="_blank">轨道控制</a> 是指利用鼠标或触屏输入来调整 3D 绘图中的摄像机方向。。要旋转摄像机，请左键点击并拖动鼠标，或在触屏上滑动。要平移摄像机，请右键点击并拖动鼠标，或在触屏上用多个手指滑动。要将摄像机移动到绘图中心更近或更远的位置，请使用鼠标滚轮或在触屏上
方向。。-> 多了一个句号

2024-04-09 09:24 UTC, unicar9 approved these changes
looks good! thanks

2024-04-09 18:08 UTC, sproutleaf approved these changes
Approve and tagging @Qianqianye @limzykenneth for merge, thanks!

2024-04-09 18:24 UTC, merged

2024-04-09 18:24 UTC, Qianqianye commented
Looks great, thanks!