[p5.js - es] Translate p5 Color and Examples 01-02 | Batch 3
bocoup/p5.js-website pull request #163
Opened 2024-04-08 01:38 UTC by MarianneTeixido

I translated the following files:
DOM:
- changed
- input

Color:
- brightness()
- color()
- green()
- hue()
- lerpColor()
- lightness()
- red()
- saturation()

Examples:
- 01_Shapes_And_Color
- 02_Animation_And_Variables

2024-04-08 02:46 UTC, holomorfo requested changes
Hola @MarianneTeixido, muchas gracias por tus traducciones. Te agrego unos comentarios menores. Saludos!
CC: @Guirdo

2024-04-08 02:46 UTC, holomorfo commented on src/content/reference/es/p5/lightness.mdx
> +      <p>objeto <a href="#/p5.Color">p5.Color</a>, arreglo de
```suggestion
      <p>Objeto <a href="#/p5.Color">p5.Color</a>, arreglo de 
```

2024-04-08 02:46 UTC, holomorfo commented on src/content/reference/es/p5/saturation.mdx
> +      <p>objeto <a href="#/p5.Color">p5.Color</a>, arreglo de
```suggestion
      <p>Objeto <a href="#/p5.Color">p5.Color</a>, arreglo de
```

2024-04-08 21:08 UTC, Guirdo approved these changes
Muchas gracias, Marianne! Aprobado 💯

2024-04-08 22:16 UTC, Guirdo commented
Disculpa, me he dado cuenta de que faltan las traducciones para [UI component](https://github.com/bocoup/p5.js-website/tree/main/src/content/ui), [About](https://github.com/bocoup/p5.js-website/blob/main/src/content/text-detail/en/about.mdx), e [Index](https://github.com/bocoup/p5.js-website/blob/main/src/content/text-detail/en/index.mdx).

¿Crearas un PR diferente para esas traducciones?

2024-04-08 22:20 UTC, holomorfo approved these changes
Muchas gracias Marianne, aprobada la traducción (y)

2024-04-09 07:03 UTC, holomorfo commented
Hi @Qianqianye this PR is aproved and ready.

2024-04-09 07:04 UTC, merged

2024-04-09 07:04 UTC, Qianqianye commented
Looks good, thanks!