[p5.js -es] Translate examples and references
bocoup/p5.js-website pull request #164
Opened 2024-04-08 01:39 UTC by EmilioOcelotl

batch 2
- ellipse()
- circle()
- line()
- point()
- quad()
- rect()
- square()
- ellipseMode()
- smooth()

batch 3
examples 03 12 13 14 15

2024-04-08 03:10 UTC, holomorfo requested changes
Hola @EmilioOcelotl muchas gracias por tus traducciones, te agrego unos comentarios y preguntas. Saludos!
CC: @Guirdo

2024-04-08 03:10 UTC, holomorfo commented on src/content/reference/es/p5/ellipse.mdx
> +        description: |
igual tengo duda la diferencia entre `|2-` y `|`

2024-04-08 03:10 UTC, holomorfo commented on src/content/reference/es/p5/ellipseMode.mdx
> +description: >
igaul que los anteriores

2024-04-08 03:10 UTC, holomorfo commented on src/content/reference/es/p5/point.mdx
> +  <p>La versión de <code>point()</code> con tres parámetros permite dibujar el punto en el espacio 3D con coordenadas x, y, y z, como en <code>point(10, 20, 30)</code>. Para hacer esto, es necesario
```suggestion
  <p>La versión de <code>point()</code> con tres parámetros permite dibujar el punto en el espacio 3D con coordenadas x, y, z como en <code>point(10, 20, 30)</code>. Para hacer esto, es necesario agregar el argumento <code>WEBGL</code> a la función <a href="/reference/p5/createCanvas">createCanvas()</a>.</p>
```

2024-04-08 03:10 UTC, holomorfo commented on src/content/reference/es/p5/square.mdx
> +title: square
falta la primera linea 
`---`

2024-04-08 22:19 UTC, holomorfo commented on src/content/reference/es/p5/circle.mdx
> +description: >
por favor actualiza este caracter al que viene en el folder en ingles si es posible

2024-04-08 22:35 UTC, Guirdo requested changes
Gracias Emilio! Te dejo un par de observaciones

2024-04-08 22:35 UTC, Guirdo commented on src/content/examples/es/13_Classes_And_Objects/03_Flocking/description.mdx
> +---
Estos tres guiones no se necesitan

2024-04-08 22:35 UTC, Guirdo commented on src/content/reference/es/p5/ellipseMode.mdx
> +  <p><code>ellipseMode(CORNERS)</code> utiliza los dos primeros parámetros como la
Devolver a su estado original, ya que es un pedazo de código

```suggestion
  <p><code>ellipseMode(CORNER)</code> utiliza los dos primeros parámetros como la
```

2024-04-10 01:35 UTC, EmilioOcelotl commented
Realicé los cambios sugeridos. Para los archivos que ya existían pero que estaban incompletos tomé como referencia los archivos de la versión en inglés, Esto quiere decir que en en algunos casos se mantiene el "description: >" Que aparece en la versión en inglés. 

Quedo al pendiente.

2024-04-10 01:48 UTC, holomorfo approved these changes
Muchas gracias, aprobado 
@Guirdo

2024-04-10 01:54 UTC, Guirdo commented
Hi @Qianqianye @limzykenneth ! This PR is ready!

2024-04-10 11:08 UTC, merged