[p5.js hi] translate example 06-10
bocoup/p5.js-website pull request #165
Opened 2024-04-08 05:14 UTC by Surbhi-Pittie

2024-04-08 05:26 UTC, Divyansh013 requested changes

2024-04-08 05:26 UTC, Divyansh013 commented on src/content/examples/hi/06_Calculating_Values/00_Interpolate/description.mdx
> +<a href='https://p5js.org/reference/#/p5/lerp' target='_blank'>lerp()</a>
use double quotes only for link

2024-04-08 05:26 UTC, Divyansh013 commented on src/content/examples/hi/06_Calculating_Values/03_Constrain/description.mdx
> +समारोह।
use function only

2024-04-08 05:26 UTC, Divyansh013 commented on src/content/examples/hi/07_Repetition/01_Color_Wheel/description.mdx
> +यह उदाहरण भिन्न-भिन्न की उपस्थिति को दर्शाता है
रंग should be used just after भिन्न-भिन्न

2024-04-08 18:47 UTC, Divyansh013 approved these changes

2024-04-09 08:01 UTC, Divyansh013 commented
@TanviKumar PTAL

2024-04-09 13:36 UTC, TanviKumar approved these changes

2024-04-09 13:43 UTC, Divyansh013 commented
We can merge this PR @limzykenneth @Qianqianye

2024-04-09 18:53 UTC, merged

2024-04-09 18:53 UTC, Qianqianye commented
Looks great, thanks!