[p5.js - es] Translate UI Component, About and Index | Resolved comments from batch 3
bocoup/p5.js-website pull request #179
Opened 2024-04-10 04:21 UTC by MarianneTeixido

I translated the following files:
- ui/es.yaml
- text-detail/
     _index.mdx
     _about.mdx

corrections in:
- saturation()
- lightness()

2024-04-10 05:19 UTC, holomorfo approved these changes
@MarianneTeixido Muchas gracias por tus traducciones, aprobado el PR.
CC: @Guirdo

2024-04-10 05:39 UTC, Guirdo requested changes
Gracias Marianne! Para el archivo index, solo traduce las líneas 11, 25 y 29. El resto devuelvelas a su estado original, por favor

2024-04-10 05:39 UTC, Guirdo commented on src/content/text-detail/es/index.mdx
>  ---
Por favor, solo traducir las líneas 11, 25 y 29. El resto devuelvelas a su estado original

2024-04-10 15:49 UTC, holomorfo approved these changes
muchas gracias, aprobado

2024-04-10 15:55 UTC, Guirdo commented
Muchas gracias, Marianne! Aprobado :100:

2024-04-10 15:55 UTC, Guirdo approved these changes

2024-04-10 15:56 UTC, Guirdo commented
Hello @Qianqianye @limzykenneth ! This PR can be merged

2024-04-11 04:17 UTC, holomorfo commented
Hi @Qianqianye, this PR is ready to be merged.

2024-04-11 05:22 UTC, merged

2024-04-11 05:23 UTC, Qianqianye commented
Looks great, thanks!