Create createA.mdx
bocoup/p5.js-website pull request #78
Opened 2024-03-28 02:27 UTC by asukaminato0721

2024-03-28 05:20 UTC, unicar9 approved these changes
Looks good

2024-03-28 18:41 UTC, sproutleaf approved these changes

2024-03-28 18:41 UTC, sproutleaf commented
Both @unicar9 and I approved. Tagging @limzykenneth @Qianqianye for merging, thank you!

2024-03-28 20:57 UTC, sproutleaf requested changes

2024-03-28 20:57 UTC, sproutleaf commented on src/content/reference/zh-Hans/p5/createVideo.mdx
> +    type: '字符串|String[]'
String[]->字符串[] 谢谢！

2024-03-29 14:30 UTC, sproutleaf approved these changes
Approve again after a small error was found!

2024-03-29 14:49 UTC, merged