[p5.js - es] Translate Vector Reference (batch 2)
bocoup/p5.js-website pull request #88
Opened 2024-03-28 14:09 UTC by ninioArtillero

2024-03-28 22:16 UTC, holomorfo approved these changes
gracias Xavier

2024-03-28 22:16 UTC, holomorfo commented on src/content/reference/es/p5/createVector.mdx
> +  pelota. Lavelocidad describe la rapidez y dirección de su movimiento.
falta espacio en La velocidad

2024-03-28 22:16 UTC, holomorfo commented on src/content/reference/es/p5/p5.Vector.mdx
> +  pelota. Lavelocidad describe la rapidez y dirección de su movimiento.
también falta espacio

2024-03-28 22:19 UTC, ninioArtillero commented on src/content/reference/es/p5/p5.Vector.mdx
> +  pelota. Lavelocidad describe la rapidez y dirección de su movimiento.
ok!

2024-03-28 22:20 UTC, ninioArtillero commented on src/content/reference/es/p5/p5.Vector.mdx
> +  pelota. Lavelocidad describe la rapidez y dirección de su movimiento.
ahí va

2024-03-29 07:47 UTC, holomorfo approved these changes
Aprobado, muchas gracias Xavier

2024-03-30 02:23 UTC, Guirdo requested changes

2024-03-30 02:57 UTC, ninioArtillero commented on src/content/reference/es/p5/p5.Vector.mdx
> +      <p>Si se omite el valor corresondiente a una componente, esta no cambiará.
Venga, gracias.

2024-03-30 03:03 UTC, Guirdo approved these changes
Muchas gracias @ninioArtillero ! Aprobado 💯

2024-03-30 03:03 UTC, Guirdo commented
Hi @Qianqianye @limzykenneth ! This PR is ready!

2024-03-30 04:08 UTC, merged

2024-03-30 04:08 UTC, Qianqianye commented
Thanks @ninioArtillero @holomorfo @Guirdo