translation: `hi`  translations for all the DOM elements
bocoup/p5.js-website pull request #94
Opened 2024-03-28 21:41 UTC by EshaanAgg

2024-04-01 05:24 UTC, TanviKumar requested changes

2024-04-01 05:24 UTC, TanviKumar commented on src/content/reference/hi/p5/createFileInput.mdx
> +  <p>दूसरा पैरामीटर, <code>एकाधिक</code>, वैकल्पिक है। यह एक बूलियन मान है जो <code>true</code> पर सेट होने पर एकाधिक फ़ाइलें लोड करने की अनुमति देता है। यदि <code>true</code> है, तो <code>callback</
Code should not be translated

2024-04-01 05:25 UTC, TanviKumar commented
@EshaanAgg PR looks good, just one minor requested change. Kindly make that, will approve once done

2024-04-01 07:28 UTC, EshaanAgg commented on src/content/reference/hi/p5/createFileInput.mdx
> +  <p>दूसरा पैरामीटर, <code>एकाधिक</code>, वैकल्पिक है। यह एक बूलियन मान है जो <code>true</code> पर सेट होने पर एकाधिक फ़ाइलें लोड करने की अनुमति देता है। यदि <code>true</code> है, तो <code>callback</
Nice catch! Will update.

2024-04-01 07:32 UTC, EshaanAgg commented
Thanks for the review @TanviKumar! I have made the required changes.

2024-04-02 10:47 UTC, TanviKumar approved these changes

2024-04-02 18:57 UTC, merged